repos:
  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0
    hooks:
      - id: gradle-task
        name: Apply Spotless
        args: ["spotlessApply", -w, -o]
        types: [kotlin]
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: pretty-format-kotlin
        args: [--autofix]
  - repo: https://github.com/redwarp/optimize-png-hooks
    rev: v1.2.0
    hooks:
      - id: optimize-png
